# Generated by Django 5.2.1 on 2025-05-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado')], max_length=20),
        ),
    ]
